### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by arashwower** [NoffearrDeathProjecT/DeathCore#40]
hi see this post !!!!
Build is faild
because : https://github.com/NoffearrDeathProjecT/DeathCore/commit/f2e528cf75ff8c9ed7882f35655ffc2a6889a83a

When compile this source has given errors:

Severity Code Description Project File Line Suppression State
Error C2039 'SpellEffectExtraData': is not a member of 'Movement' game D:\src\server\game\Entities\Unit\Unit.h 1686

**Comment by alexandre433** [comment]
That commit was 13 days ago

**Comment by arashwower** [comment]
now when I compile source given error!! not problem ?:)

**Comment by alexandre433** [comment]
I'll take care of it just wait a bit please ^^

**Comment by Bodeguero** [comment]
@arashwower Please, before opening any kind of request telling us about bugs talk about something we do not know and not something we already know - we work with the Travis CI System to test the Linux platform and AppVeyor for testing on the Windows platform - please Do not open something unnecessary like you did now!

PS: Soon we will be making the corrections so that the Build is fixed - before posting something like this inultiu see our test tools if in case of error or try to compile therefore will be with error too!

Grateful!
